set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

#set toolchain path
set(INSTALL_DIR /usr/share/toolchains)
set(TOOLCHAIN_DIR ${INSTALL_DIR}/gcc-arm-11.2-2022.02-x86_64-arm-none-linux-gnueabihf)
set(TARGET_SYSTEM arm-none-linux-gnueabihf)
set(SYSROOT_DIR ${TOOLCHAIN_DIR}/${TARGET_SYSTEM}/libc)

set(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/bin/${TARGET_SYSTEM}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/${TARGET_SYSTEM}-g++)
set(CMAKE_SYSROOT ${SYSROOT_DIR})
SET(CMAKE_CXX_FLAGS " -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard --sysroot=${SYSROOT_DIR}")
SET(CMAKE_C_FLAGS ${CMAKE_CXX_FLAGS})
SET(CMAKE_EXE_LINKER_FLAGS "--sysroot=${SYSROOT_DIR}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
